fsm/deciders.go
fsm/deciders_test.go
fsm/fsm.go
fsm/fsm_models.go
fsm/fsm_test.go
fsm/replicators_test.go

refactor outcomes into a single Outcome stuct

---

fsm/fsm.go
fsm/interceptors.go
fsm/interceptors_test.go

test that dedupi.ng completes is possible

switch to a pointer for outcome passed to interceptors,

---

fsm/client.go
fsm/client_test.go
fsm/fsm.go
migrator/migrator.go

fsm client

---

fsm/client.go
fsm/client_test.go

dont serialize string inputs in client signals

---

activity/handler.go
activity/handler_test.go
activity/interceptors_test.go
activity/worker.go
activity/worker_test.go
testing/stubs.go

add a short lived stub workflow
add special casing of string in / out to activity handler

testing and activity tweaks

---

activity/handler.go
fsm/client.go
fsm/client_test.go

/cc @ryanbrainard this look ok?
https://github.com/sclasen/swfsm/blob/fd28882d1cdad511f3c2ffeb7527cebeda7fd026/fsm/client.go#L199-L208

Retry get state on eof

---

activity/handler_test.go
activity/worker.go
activity/worker_test.go

fixes immediate bug.
larger question do we care to differentiate between nil and ""

Fix activity worker nil result

---

fsm/client.go

Handle null results in snapshots

---

fsm/client.go
fsm/client_test.go
fsm/fsm.go
fsm/fsm_models.go

FSMClient enhance!

---

activity/coordinated_worker.go
activity/worker.go

Cancel the activity on receiving "unknown execution" as well as "unknown activity."

Cancel on unknown workflow execution as well.

---

testing/listener.go

Now that we have the `ComposedDecisionInterceptor`, this changes `DefaultActivityInterceptor` to an explicit `FailActivitiesOnce` option for `TestFailOnceActivityInterceptor ` to be composed into other interceptors.

Add option for failing activities once in tests

---

fsm/client.go
fsm/fsm_models.go
fsm/fsm_test.go

that fsm data structs may implement. if they do, use the tags when starting or continuing a workflow

introduce a taggable interface

---

fsm/interceptors.go
fsm/interceptors_test.go

only start timer on first decision
better check for start of workflow

fix ordering bug

---

fsm/interceptors.go
fsm/interceptors_test.go

used by workflows that have persistent activities to signal they are ready to continue

add handling of ContinueSignal to ManagedContinuations interceptor.

---

Makefile
migrator/migrator.go

And drop a use of code.google.com.

Fix up migrator panic message.

---

fsm/correlator.go

Should delete from Cancellations, not Activities

Fix EventTypeRequestCancelExternalWorkflowExecutionFailed

---

fsm/client.go

surface some extra funcs to make admin tasks (such as restarting terminated workflows) easier.

Surface serialized state

---

fsm/client.go

This updates `FSMClient.GetSnapshots()` to pull in multiple pages of history events. 
We probably want to break out these snapshots into somewhere else (especially while it's experimental... maybe only in swfsmx? thoughts?), but just wanted to make this small change for now so swfsmx can view the full workflow history.

Fix GetSnapshots() to iterate history event pages

---

fsm/fsm.go
poller/poller.go

change decision task poller to read pages until told to stop, 

---

activity/coordinated_worker.go
activity/worker.go
activity/worker_test.go
fsm/client.go
fsm/client_test.go
fsm/correlator_test.go
fsm/deciders.go
fsm/fsm.go
fsm/fsm_test.go
fsm/replicators.go
handler/handler.go
log/log.go
migrator/migrator.go
migrator/migrator_test.go
poller/poller.go
testing/stubs.go

by those that desire to do so
for #68  @uberbrodt  does this solve the issue?
```go
import "log"
import swflog "github.com/sclasen/swfsm/log"
swflog.Log = log.New(...)
```

add and use a Mutable log.Logger so that it can be modified

---

fsm/deciders.go

Super small change, but the log output was confusing me.

Log correct message in fsm.CancelWorkflow

---

fsm/fsm.go
poller/poller.go

Log more about decision tasks and their included events.

more decision poll logging

---

activity/coordinated_worker.go

cancel on start error uses input if update nil

---

fsm/deciders.go
fsm/deciders_test.go

Moves control deciders into this project.

Migrate over deciders from control

---

poller/poller.go

Fixes concurrent map access found by [go1.6](https://github.com/golang/go/blob/0ed70efc6b7ec096603c58f27c2668af3862bb3c/doc/go1.6.html#L300).

guard registered pollers map with mutex

---

testing/example_test.go

basic testing setup boilerplate and testListener usage.
/cc @ryanwalls   for #26

testing usage boilerplate examples

---

poller/poller.go

zero out registered pollers when StopPollers finishes

---

fsm/deciders.go

Decider for EventTypeTimerCanceled

---

fsm/interceptors.go
fsm/interceptors_test.go

This interceptor ended up being generic enough to be used in a different fsms.

Add generic startcancel interceptor

---

testing/listener.go
testing/stubs.go
testing/stubs_test.go

warning will likely cause testing havoc on FSMs with missing throttle handling :)
/cc @ryanbrainard @dpiddy @fabiokung

ThrottleOnce test interceptors for signals, timers, children

---

fsm/client_test.go
fsm/fsm.go
fsm/fsm_test.go

make allowPanics public to allow for easier debug during testing

---

fsm/interceptors.go

add logging of number of events in managed continuations

---

activity/worker.go
fsm/client_test.go
fsm/fsm.go
fsm/fsm_test.go
fsm/interceptors_test.go

make system serializer public

---

fsm/s3serializer/serializer.go

Log some info in S3Serializer.

s3serializer logs

---

fsm/fsm.go

If the fsm serializer is expensive, such as an S3Serializer, saves a lot of probably useless roundtrips.

stash outcome.Data with json

---

fsm/fsm.go
fsm/fsm_models.go
fsm/fsm_test.go

use gobs for stashing

---

activity/coordinated_worker_test.go
activity/worker.go
activity/worker_test.go

Due to bool zero values of false they were not doing
much.
Broken out from #152

rework coordinated worker tests

---

activity/coordinated_worker.go
activity/coordinated_worker_test.go
activity/handler.go
activity/worker_test.go

add Finish coordinated worker hook

---

fsm/fsm.go
fsm/fsm_models.go
fsm/fsm_test.go

Add TaskErrorHandler that allows recovering from errors outside Deciders

---

fsm/correlator.go
fsm/correlator_test.go

Fix activity info from signal

---

activity/coordinated_worker.go

Make cancel channel in coordinated worker buffered

---

vendor/github.com/golang/protobuf/LICENSE
vendor/github.com/golang/protobuf/jsonpb/jsonpb.go
vendor/vendor.json

/cc @ryanwalls I think this is why your build was failing, can you pull this down and see if `make install` works?

vendor jsonb

---

fsm/fsm.go
fsm/fsm_test.go
fsm/interceptors.go
fsm/interceptors_test.go

Closes #184.
The philosophy here is to prevent some SWF errors by default for new FSMs.  SWF complains if there are multiple close decisions or if the close decision is not at the end.

Create default decision interceptor and individual interceptors for close decisions

---

fsm/deciders.go
fsm/deciders_test.go

Adds a composed decider for `OnChildStartedOrAlreadyRunning`. This can be used a the inverse case of `OnChildStartFailedAndNotAlreadyRunning`.

Add OnChildStartedOrAlreadyRunning

---

testing/listener.go

Replace `RegisterXInterest` methods with auto-registration internal to the `TestListener`. This means that tests can just call the `AwaitX[For]` methods without having to pre-register interest for a given workflow id. All workflow ids are now recorded automatically, so there is a small risk of overrunning the channels, but in that case, the listener will not block and fail fast. If we need more capacity, `interestChannelSize` can always be increased, but 1000 was used before and even with explicit registration and didn't cause any known problems.

Auto register interest

---

fsm/fsm.go

use a configurable number of polling goroutines.

Multi poller

---

readme.md

misc: Correct name of vendor.json
