sclasen/swfsm

- fsm/correlator_test.go
- fsm/fsm.go
- fsm/fsm_models.go
- fsm/fsm_test.go
/cc @fabiokung @dgouldin
With a bit of inspiration from http://www.boost.org/doc/libs/1_39_0/libs/statechart/doc/rationale.html#ErrorHandling
Basically there are 2 types of errors. Errors in the FSM which are generally unrecoverable without a config or code change and Decision errors/panics which may be. 
If a DecisionErrorHandler can successfully recover, we continue processing the decisionTask, if not, we abandon any further processing.
```go
//DecisionErrorHandler is the error handling contract for panics that occur in Deciders.
//If your DecisionErrorHandler does not return a non nil Outcome, any further attempt to process the decisionTask is abandoned and the task will time out.
type DecisionErrorHandler func(ctx *FSMContext, event swf.HistoryEvent, stateBeforeEvent interface{}, …
```
> refactor error handling/reporting completely

- Makefile
- fsm/fsm.go
- fsm/fsm_models.go
Enhanced error handling / recovery behavior.
Instead of simply abandoning processing of a decisionTask that has an nil Outcome from the DecisionErrorHandler or an FSMError, we instead just respond to the decisionTask with 3 state markers (which do not initiate any further decisions on their own).
* the standard state marker -> `SerializedState`
* the standard correlator marker -> `EventCorrelator`
* an ErrorState marker ->  `SerializedErrorState` (the HistoryEvent that caused the error, the range of `EventID`s that are unprocessed)
On any subsequent DecisionTask, the FSM will notice an error marker, which places the workflow in an error mode. 
It will have already deserialized the latest "good" copy of the `SerializedState` and `EventCorrelator` from the previous markers.
FSM then …
> update error handling to allow error recovery as well

- fsm/fsm.go
- fsm/interceptors.go
- fsm/interceptors_test.go
Potential usages. 
* DecisionInterceptor.BeforeTask: load more history/filter history before state is deserialized
* DecisionInterceptor.BeforeDecision: fix or migrate stateData or state.
* DecisionInterceptor.AfterDecision: Make additional Decisons based on the full Outcome, filter Decisions from Outcome, e.g. make sure only one Complete or Continue Workflow decision is in the Outcome.
> add DecisionInterceptor which gives the ability to intercept decision tasks at key points in the decision lifecycle

- poller/poller.go
- testing/listener.go
- testing/stubs.go
Rework the testing utils to make setup boilerplate less painful
Also insert per-test Decision and Activity TaskLists so tests can be run continuously without falling victim to the phantom task assignment bug.
> Testing fixes

- activity/worker.go
- activity/worker_test.go
when the `ActivityWorker` is configured with `BackoffOnFailure = true`, then on activity failures, look up the event correlator from workflow history, and read the number of times the current activity has retried, backing off exponentially, up to `MaxBackoffSeconds`.
/cc @fabiokung
> worker managed backoff on activity failures

- activity/coordinated_worker.go
- activity/coordinated_worker_test.go
- activity/handler.go
- activity/worker.go
- activity/worker_test.go
- fsm/correlator.go
- fsm/correlator_test.go
- fsm/deciders.go
- fsm/deciders_test.go
- fsm/fsm.go
- fsm/fsm_models.go
- fsm/fsm_test.go
- migrator/migrator.go
- testing/listener.go
- testing/stubs.go
CoordinatedActivityHandlers are now constructed from 3 funcs.  No more convoluted LongRunningActivityCoordinator mess-o-channels
* Start: start the activity, when this returns, an ActivityStartedSignal is sent to the workflow, which will also let it see the ActivityTaskStartedEvent (which doesnt trigger a decision)
* Work: Do some piece of work, but dont block forever. return true,nil,nil if you want to keep going and Work will be called again. Return false, result, error if you want to finish/fail the activity. This gives an opportunity for the coordinator to cancel the work if necessary after each Tick.
* Cancel: Called after Work yields when the activity has been canceled. Lets you shutdown the activity before RespondActivityTaskCanceled is called.
/cc @ryanbrainard @fabiokung
> rework coordinated handler, was not useful in practice

- Makefile
- activity/coordinated_worker.go
- activity/coordinated_worker_test.go
- activity/handler.go
- activity/handler_test.go
- activity/interceptors.go
- activity/interceptors_test.go
- activity/worker.go
- activity/worker_test.go
... and implement them as a regular `ActivityTaskHandler` so we can get rid of the special case (`LongRunningActivityTaskHandler`).
* Interceptors now work for `CoordinatedActivityTaskHandlers` too.
* `Tick()` is not immediately called after `Start()`, only after `tickMinInterval`.
* support for responding to cancel requests from `ActivyTaskHandlers`.
* `LongRunningActivityTaskHandler` goes away.
I flipped the logic on some if-else chains to reduce nesting and make them simpler, so it may be a bit difficult to read diffs, sorry! It was mostly:
```go
// from
func work() {
if something {
// happy path
} else {
// sad path
}
}
// to
func work() {
if !something {
// sad path
return
}
// happy path
}
```
/cc @sclasen
> Rate limit coordinated workers

- fsm/client.go
- fsm/client_test.go
- fsm/fsm.go
- fsm/fsm_models.go
This is a first pass at walking the SWF history to produce "snapshots" of a FSM. This produces a data structure where it is much easier to see the states from the markers and the events from starts, signals, activities, etc in one consolidated view without much of the clutter from SWF and intermediary states. Here is an example of 11 SWF events boiled down to 3 snapshots:
```
[{
"State": {
"ID": 11,
"Timestamp": "2015-06-14T01:54:14Z",
"Version": 2,
"Name": "attached",
"Data": {
...
}
}, "Event": null
}, {
"State": {
"ID": 5,
"Timestamp": "2015-06-14T01:54:13Z",
"Version": 1,
"Name": "attached",
"Data": {
...
}
},
"Event": {
"Type": "WorkflowExecutionSignaled",
"Name": "Domain.Attach",
"Version": "",
"Source": "",
"Target": "",
"Input": {...},
"Output": null
}
}, {
"State": {
"ID": 1, …
```
> Add FSMClient.GetSnapshots

- activity/interceptors.go
- activity/worker.go
- poller/poller.go
- testing/listener.go
- testing/stubs.go
I have been running into many problems with https://github.com/sclasen/swfsm/pull/57; however, it does not appear to be because of this change directly, but rather the extra time this change introduces to tests.  Because there is still utility in this interceptor (and other logging introduced during debugging), I am going to pull this in as is, but disabled by default.
> TestFailOnceActivityInterceptor - available but disabled by default.

- fsm/client.go
- fsm/fsm_models.go
- fsm/fsm_test.go
- handler/handler.go
/cc @dpiddy @fabiokung this may help (or not) with the heartbeat timeouts we have been seeing where latencies get high enough for the heartbeat timeout to get reached.
here we use an httpclient that has a 2 second timeout, only for sending heartbeats.
> use a client with 2 second timeout when sending heartbeats

- fsm/client.go
- fsm/correlator_test.go
- fsm/fsm.go
- fsm/fsm_models.go
- fsm/fsm_test.go
- fsm/interceptors_test.go
- fsm/replicators_test.go
so we can restart failed workflows from console/cli/programatically, and not lose stateVersion stateName, etc.
/cc @fabiokung :(
> back to StartFSMWorkflowInput, 

- log/log.go
Making a simple interface and using that as the type for the mutable logger will allow others to inject any class that basically implements the log package. This is pulled from the https://github.com/Sirupsen/logrus package. For my purposes, it will allow me to catch errors from the code and send them to Airbrake.
> Make the mutable logger an interface

- fsm/client.go
- fsm/client_test.go
- fsm/fsm_models.go
This changes `FSMSnapshot` from "fuzzy compacting" `HistoryEvents` in the gigantic `switch`to just passing through all the events as-is, but changing the event attributes into a unified `map[string]interface` for easier client access. This also includes the correlation data and referencing events in snapshots.
> Generic Snapshots

- awsinternal/jsonutil/unmarshal.go
- fsm/client.go
- fsm/client_test.go
- fsm/fsm_models.go
- fsm/snapshots.go
Adds support to read snapshots from a stream (i.e. a JSON file of SWF history events output from the AWS CLI). Because these files use AWS's special JSON RPC format, I had to pull in their internal JSON decoder. Let me know if there was a better way to do this.
This also adds a `HistoryEventIterator` for more flexibility between the producers and consumers. Along with streams, iterators can also be created from `WorkflowExecution`s for more efficient look ups by tag and future support for querying by runID.
> Snapshots streams

- fsm/client_test.go
- fsm/finder.go
I mistakenly thought that `ReverseOrder` meant descending,
but the default is already descending, so `ReverseOrder`
changes the results to be ascending. This reverses the sort logic
accordingly.
> Fix FSMClient.FindAll ordering

- Godeps/_workspace/src/github.com/stretchr/testify/mock/mock.go
- fsm/client_test.go
- fsm/history_segments.go
This fixes a bug with the `HistorySegment.State.Data` pointing being the same for all segments. It also adds unit tests to avoid this in the future and records the `SerializedErrorState` to include all the types of markers.
> Fix history segment state data + tests + error state

- fsm/fsm.go
- fsm/fsm_models.go
- fsm/fsm_test.go
When a non-handled error was detected, it was being added to the `ErrorMarker`, but then returning the error from `Tick`, which never completed the decision. This serializes the error in the marker and returns a `nil` error so that it gets properly recorded.
> Record notHandled error in SerializedErrorState

- fsm/client.go
- fsm/client_test.go
- fsm/history_segments.go
- fsm/history_segments_test.go
This replaces the custom `HistoryEventIterator` with use of the `GetWorkflowExecutionHistoryPages` that already exists in the SWF client. The `HistorySegmentor` is updated to support this and now has callbacks for listening for events during the paging.
> Prefer GetWorkflowExecutionHistoryPages to HistoryEventIterator

- fsm/fsm.go
Otherwise they will show up as %\!q(...) and %\!s(...) on logs:
```
component=FSM name=... action=tick workflow=%!s(*string=0xc820462270) workflow-id=%!s(*string=0xc820462190) at=decider-error err="..."
```
> dereference string pointers before using them with fmt

- fsm/client.go
- fsm/client_test.go
- fsm/finder.go
... and usable without a `fsm.FSMClient`. Tests in `fsm/client_test.go` still cover all the functionality exposed by `fsm.Finder`.
/cc @ryanbrainard
> make fsm.Finder public

- activity/coordinated_worker.go
this allows for any goroutines started in Start to be stopped before exiting the activity
> call Cancel if signalStart fails

- fsm/fsm_test.go
Fixes #111 
Users get deserialization errors if they don't setup the input correctly.
> Update example to use StartFSMWorkflowInput

- activity/dispatchers.go
- activity/dispatchers_test.go
Register this dispatcher with a ShutdownManager. 
Used in your ActivityWorkers, it will count in-flight activities.
It doesnt ack shutdowns until the number of in flight activities are zero.
> countdown dispatcher

- fsm/deciders.go
Super simple change, but I found it useful. How do we feel about logging stuff like this?
> If a timer failed, log the reason

- fsm/dispatchers.go
- fsm/dispatchers_test.go
- fsm/fsm.go
- fsm/replicators.go
ReplicationHandlers may receive events out of order.
Document it, and add a new DIspatcher (`GoroutinePerWorkflowDispatcher`) that can be used to guarantee delivery in order within a single decider process (order is still not guaranteed across multiple decider processes).
> Out of order replication

- activity/coordinated_worker.go
- activity/worker.go
- fsm/client.go
- fsm/finder.go
- fsm/fsm.go
- migrator/migrator.go
- poller/poller.go
Many errors have spaces, such as this:
```
error=handler: Throttling: Rate exceeded
```
> standardize on error=%q

- activity/coordinated_worker_test.go
- activity/interceptors_test.go
- activity/worker.go
- activity/worker_test.go
The purpose of this would be to allow users to handle polling themselves, but still be able to use the handling that is built into the ActivityWorker.  
I also considered exposing `handleWithRecovery` so that they could still gracefully recover from panics without implementing themselves.  Thoughts?
My purpose for this... We are scheduling long running tasks to run on ECS.  These tasks can take weeks, so we separated the polling out into stateless services that can be killed without ramifications.  These stateless services call the ecs.RunTask api when they get a task in.  Now I want the containers running on ECS to use ActivityWorker, but without the polling.
> Expose activity handler so users can poll independently.

- activity/swfconstants.go
- activity/worker.go
- activity/worker_test.go
Closes #161 
Logging format is very consistent... wasn't sure how to make the truncate log message fit within the pattern.
> Truncate long failure reasons in activity worker

- Makefile
#169 introduced a few things which caused problems running `make` locally - a imports command had arguments out of order, and we were trying to format vendored code.
This fixes that.
> Fix imports command, only fmt our code

- fsm/deciders.go
- fsm/deciders_test.go
This introduces an inverse `OnDataUnless` handler to avoid having to creating special negated predicates.
> Add OnDataUnless

- fsm/jsonpbserializer/jsonpbserializer.go
We weren't actually calling the unmarshal on it, just using the default.
> jsonpb: Use passed in Unmarshaler

- .travis.yml
- activity/worker.go
- fsm/fsm.go
- fsm/fsm_panic_test.go
- fsm/fsm_test.go
- internal/panicinfo/panic.go
- internal/panicinfo/panic_test.go
- log/log.go
Closes #135 
When a panic occurs, this will walk back up the caller tree to find out where the panic occured, and log that information. e.g:
```
2016/10/03 14:37:41 component=FSM name= at=decide-panic-recovery func="github.com/sclasen/swfsm/fsm.TestPanicRecovery.func1" file="/home/lstoll/src/github.com/sclasen/swfsm/fsm/fsm_test.go:296" error="can you handle it?"
```
> Log Panic Site in Decider/Activity recovery handler

- fsm/client.go
- fsm/client_test.go
dogwood-control ftests (luckily!) caught a bug in https://github.com/heroku/dogwood/pull/1706 where the loop never breaks when no items are returned. The actual fix is just one line (db3ef1bc42dc1e42825b4ce132020a1e3aee755a), but I also merged `cont` and `done` since they are really the same concept to improve the logic flow.
> Find all walk empty break

- fsm/client_test.go
- fsm/finder.go
Changes `finder.setMostSelectiveTimeFilter` to return the `ClosedTimeFilter` instead of the  `StartTimeFilter` for what to send to SWF for the list closed API call. Note, this is just an optimization without any functional change because `finder.applyInputLocally` still does filtering locally. This is just switching the order to avoid having SWF return a huge list of closed workflows, only to be filtered locally.
See https://github.com/heroku/dogwood/issues/1749#issuecomment-397136918 for why we need this.
> Fix most selective time filter

- fsm/finder.go
- fsm/fsm.go
- fsm/interceptors.go
- fsm/interceptors_test.go
To break an import cycle (and put code where it really belongs), move the `CloseWorkflowRemoveIncompatibleDecisionInterceptor` into swfsm. Also exposes `CloseDecisionTypes` and `CloseDecisionIncompatableDecisionTypes` for tests to access.
> Add CloseWorkflowRemoveIncompatibleDecisionInterceptor
